### ISSUE TITLE
[CRITICAL ERROR] Build Failed. 

### ISSUE THREAD

**Issue by SticksDev** [bdentler/mechanicalmustang2019#5]
Welp, gradel is screaming at me

https://pastebin.com/hJxn1mMq

So, what do we do now?

@bdentler

**Comment by Thatcooldevguy** [comment]
tanner_sommers@tannersommers-PC:~/mechanicalmustang2019$ ./gradlew build
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp

BUILD SUCCESSFUL in 4s
4 actionable tasks: 4 executed

:) 

The error was that JRE-10 was installed, not JAVA JRE SE 11. 

[issue closed]

**Comment by SticksDev** [comment]
tanner_sommers@tannersommers-PC:~/mechanicalmustang2019$ ./gradlew build
Picked up _JAVA_OPTIONS:   -Dawt.useSystemAAFontSettings=gasp

BUILD SUCCESSFUL in 4s
4 actionable tasks: 4 executed

:) 

The error was that JRE-10 was installed, not JAVA JRE SE 11. 

[issue closed]
